const CONFIG = {
    SERVER_URL : 'http://localhost:8080',
    IP_ERROR : 'ip-error',
    CONNECTION_TYPE_ERROR : 'connection-type-error',
    CONNECTION_TYPE_MESSAGE : 'connection-type-message',
    CONNECTION_TYPE_VIDEO_TRANSMITTER : 'connection-type-video-transmitter',
    CONNECTION_TYPE_VIDEO_RECEIVER : 'connection-type-video-receiver',
    MAX_RECONNECTION_ATTEMPTS : 1,
    TIME_OUT : 'time-out',
    CONNECT : 'connect',
    CONNECT_ERROR  : 'connect_error',
    DISCONNECT : 'disconnect',
    CREATE_ROOM : 'create-room',
    CREATE_ROOM_SUCCESS : 'create-room-success',
    CREATE_ROOM_ERROR : 'create-room-error',
    JOIN_ROOM : 'join-room',
    JOINED : 'joined',
    JOINED_ANOTHER_SESSION : 'joined-another-session',
    JOIN_ROOM_SUCCESS : 'join-room-success',
    JOIN_ROOM_ERROR : 'join-room-error',
    JOIN_ROOM_REQUEST : 'join-room-request' ,
    WAIT_FOR_APPROVAL : 'wait-for-approval',
    APPROVE_REQUEST : 'approve-request',
    REJECT_REQUEST : 'reject-request',
    REQUEST_APPROVED : 'request-approved',
    REQUEST_REJECTED : 'request-rejected',
    LEAVE_ROOM : 'leave-room',
    TERMINATE_ROOM : 'terminate-room',
    LEFT_ROOM : 'left-room',

    MESSAGE : 'message',
    MESSAGE_ALL : 'message-all',
    JOIN_VIDEO : 'join-video',
    LEAVE_VIDEO : 'leave-video',
    VIDEO_FRAME : 'video-frame',
};
export default CONFIG;